# Generated by Django 5.2.5 on 2025-10-09 21:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rfq_master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRF",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qrf_no",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("revision_date", models.DateField(blank=True, null=True)),
                ("client_name", models.CharField(max_length=255)),
                ("consultant_name", models.CharField(blank=True, max_length=255)),
                ("job_site", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        default="DRAFT",
                        help_text="DRAFT / SUBMITTED / APPROVED / REJECTED",
                        max_length=30,
                    ),
                ),
                ("design_code", models.CharField(blank=True, max_length=50)),
                ("serviceability_code", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qrf_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qrf_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_engineer",
                    models.ForeignKey(
                        help_text="User (Sales) who created the QRF",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qrf_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rfq_master.region",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qrf_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRFBaseCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Main Col bases'", max_length=100
                    ),
                ),
                (
                    "dropdown",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AS_PER_DESIGN", "As per design"),
                            ("FIXED", "Fixed"),
                            ("PINNED", "Pinned"),
                            ("HINGED", "Hinged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_conditions",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFBracingCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "dropdown",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AS_PER_DESIGN", "As per design"),
                            ("FULL_HT_CROSS", "Full height cross"),
                            ("DIAGONAL", "Diagonal"),
                            ("K_BRACE", "K-Brace"),
                            ("NONE", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bracing_conditions",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFBuildingAddition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                ("value", models.BooleanField(default=False)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFBuildingUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("MAIN", "Main Building"),
                            ("LEAN_TO", "Lean-To Shed"),
                        ],
                        default="MAIN",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name like Main-1, Lean-To-1, Lean-To Loading Shed",
                        max_length=100,
                    ),
                ),
                (
                    "frame_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RF", "RF (Main Building)"),
                            ("LEAN_TO", "Lean-To"),
                            ("CRANE", "Crane Support"),
                            ("CANOPY", "Canopy"),
                            ("OPEN", "Open Structure"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Used to order lean-tos sequentially"
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_units",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFBuildingParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parameter_type",
                    models.CharField(
                        choices=[
                            ("WIDTH", "Width (m)"),
                            ("LENGTH", "Length (m)"),
                            ("CLEAR_HEIGHT", "Clear Height (m)"),
                            ("BASE_PLATE", "Base Plate Bottom With ref to FFL"),
                            ("ROOF_SLOPE", "Roof Slope"),
                            ("BAY_SPACING", "Bay Spacing (C/C)"),
                            ("INTERNAL_COLUMN", "Internal Column Nos & Spacing"),
                            ("END_WALL_COLUMN", "End Wall Column Spacing"),
                            ("BWALL_FRONT", "B/wall Condition : Front Side wall"),
                            ("BWALL_BACK", "B/wall Condition : Back Side wall"),
                            ("BWALL_LEFT", "B/wall Condition : Left End wall"),
                            ("BWALL_RIGHT", "B/wall Condition : Right End wall"),
                            ("FUTURE_EXPANSION", "Future Expansion"),
                            ("ROOF_EXTENSION", "Roof Extension"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dimension_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=255)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meter", "Meter"),
                            ("degree", "Degree"),
                            ("number", "Number"),
                            ("boolean", "Yes/No"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "end_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C/C_COL", "C/C of Column"),
                            ("O/O_STEEL", "O/O of Steel"),
                            ("WITH_CANTILEVER", "With Cantilever"),
                            ("WITHOUT_CANTILEVER", "Without Cantilever"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional data for special cases",
                    ),
                ),
                (
                    "building_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="qrf.qrfbuildingunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFCageLadder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cage_ladders",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFCanopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("nos", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "width_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "clear_height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type_of_canopy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLOPE_AWAY", "Slope away from building"),
                            ("SLOPE_TOWARDS", "Slope towards building"),
                            ("FLAT", "Flat"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("soffit_required", models.BooleanField(default=False)),
                ("gutter_and_downtake", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canopies",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFCrane",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "capacity_mt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("nos", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "span_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height_reference",
                    models.CharField(
                        blank=True, help_text="Top of crane beam, etc.", max_length=100
                    ),
                ),
                ("tandem_operation", models.BooleanField(default=False)),
                ("walkway", models.BooleanField(default=False)),
                (
                    "walkway_width_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("walkway_handrail", models.BooleanField(default=False)),
                ("cage_ladder", models.BooleanField(default=False)),
                ("crane_beam_by", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cranes",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFFascia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("type_of_fascia", models.CharField(blank=True, max_length=100)),
                ("fascia_upto", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fascias",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFFramedOpening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("nos", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "width_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("door_type", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="framed_openings",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFGravityLoading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "load_value",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gravity_loadings",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFLouver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("nos", models.PositiveIntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="louvers",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFMezzanine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "ll_kn_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Live Load (kN/sqm)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dl_kn_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dead Load (kN/sqm)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cl_kn_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Collateral Load (kN/sqm)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "slab_thk_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Slab Thickness (mm)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "including_deck",
                    models.BooleanField(
                        default=False,
                        help_text="True = Including Deck, False = Excluding Deck",
                    ),
                ),
                (
                    "deck_sheet_thk_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deck Sheet Thickness (mm)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("handrails", models.BooleanField(default=False)),
                (
                    "nos_of_staircase",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("staircase_treads", models.CharField(blank=True, max_length=100)),
                ("shear_studs", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mezzanines",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFMinThicknessCriteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Label, e.g. 'B/U Web'", max_length=100),
                ),
                (
                    "dropdown",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AS_PER_DESIGN", "As per design"),
                            ("6MM", "6 mm"),
                            ("8MM", "8 mm"),
                            ("10MM", "10 mm"),
                            ("12MM", "12 mm"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="min_thickness_criteria",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFPartitionWall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("type_of_sheeting", models.CharField(blank=True, max_length=100)),
                ("single_or_double_side", models.CharField(blank=True, max_length=50)),
                ("permanent_or_removable", models.CharField(blank=True, max_length=50)),
                ("bwall_condition", models.CharField(blank=True, max_length=100)),
                ("girt_condition", models.CharField(blank=True, max_length=100)),
                ("insulation", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partition_walls",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFPipeRackCableTray",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "height_from_ffl_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bracket_width_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("one_side_or_two", models.CharField(blank=True, max_length=50)),
                (
                    "loading_kg_per_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("supporting_structure_required", models.BooleanField(default=False)),
                (
                    "supporting_structure_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Hot Rolled / Cold Formed",
                        max_length=100,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipe_rack_trays",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFRoofMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=50)),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "acph",
                    models.CharField(
                        blank=True, help_text="Air changes per hour", max_length=50
                    ),
                ),
                ("louvers", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roof_monitors",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFSafetyLifeLineSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_life_line_systems",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFSecondaryDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Purlin spacing'", max_length=100
                    ),
                ),
                (
                    "dropdown",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AS_PER_DESIGN", "As per design"),
                            ("900", "900 mm"),
                            ("1000", "1000 mm"),
                            ("1200", "1200 mm"),
                            ("1500", "1500 mm"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_details",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFSeismicLoading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "dropdown",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AS_PER_DESIGN", "As per design"),
                            ("FULL_HT_CROSS", "Full height cross"),
                            ("DIAGONAL", "Diagonal"),
                            ("K_BRACE", "K-Brace"),
                            ("NONE", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seismic_loadings",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRFSheetingDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label like 'Roof Sheeting', 'Gutter', 'Ridge Vent', etc.",
                        max_length=100,
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '0.475mm thk TCT Color' or 'Galvalume pipe'",
                        max_length=255,
                    ),
                ),
                (
                    "additional_requirement",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Sub purlin requirement', 'Header pipe arrangement'",
                        max_length=255,
                    ),
                ),
                (
                    "mesh",
                    models.BooleanField(default=False, help_text="Is mesh required?"),
                ),
                (
                    "insulation",
                    models.CharField(
                        blank=True,
                        help_text="Optional e.g. 'Mesh', 'Fiber', etc.",
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheeting_details",
                        to="qrf.qrf",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QRFWindLoading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label, e.g. 'Roof member'", max_length=100
                    ),
                ),
                (
                    "dropdown",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AS_PER_DESIGN", "As per design"),
                            ("FULL_HT_CROSS", "Full height cross"),
                            ("DIAGONAL", "Diagonal"),
                            ("K_BRACE", "K-Brace"),
                            ("NONE", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "qrf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wind_loadings",
                        to="qrf.qrf",
                    ),
                ),
            ],
        ),
    ]
