# Generated by Django 5.2.5 on 2025-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrf",
            name="serviceability_code",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
